---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'android/**'
      - 'build/**'
      - 'doc/**'
      - 'python/**'
      - 'subprojects/**'
      - 'systemd/**'
      - 'win32/**'
    branches:
      - master
      - actions
  pull_request:
    paths-ignore:
      - 'android/**'
      - 'build/**'
      - 'doc/**'
      - 'python/**'
      - 'subprojects/**'
      - 'systemd/**'
      - 'win32/**'
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}

      - uses: actions/setup-python@v1

      - name: Install dependencies
        run: |
          brew install \
            meson ninja \
            fmt \
            boost \
            googletest \
            icu4c \
            ffmpeg \
            libnfs \
            yajl \
            libupnp \
            libid3tag \
            chromaprint \
            libsamplerate \
            libsoxr \
            flac \
            opus \
            libvorbis \
            faad2 \
            wavpack \
            libmpdclient

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: output
          setup-options: -Ddocumentation=disabled -Dtest=true
          meson-version: 0.56.0
